# Use postgres/example user/password credentials

services:

  migrations:
    profiles: [ "dev" ]

    build:
      context: .
      target: migrations
    environment:
      ConnectionStrings__ApiContext: "Server=db;Database=vacinas;Username=postgres;Password=postgresssss;Port=5432"
    command:
      - "--connection"
      - "Server=db;Database=vacinas;Username=postgres;Password=postgresssss;Port=5432"

  api:
    profiles: [ "dev" ]

    build:
      context: .
      target: api
    environment:
      ConnectionStrings__ApiContext: "Server=db;Database=vacinas;Username=postgres;Password=postgresssss;Port=5432"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "8080:8080"

  db:
    image: postgres:18-alpine
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: "postgresssss"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d vacinas" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
  nuget-cache:
