// <auto-generated />
using System;
using Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20260909154304_Initial Create")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CartaoVacinaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("LastModificationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PictureUpload")
                        .HasColumnType("text");

                    b.Property<Guid?>("RacaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CartaoVacinaId");

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("RacaId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("Api.Models.AplicacaoVacina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CartaoVacinaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataAplicacao")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("LastModificationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VacinaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CartaoVacinaId");

                    b.HasIndex("VacinaId");

                    b.ToTable("AplicacoesVacina");
                });

            modelBuilder.Entity("Api.Models.CartaoVacina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastModificationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CartoesVacina");
                });

            modelBuilder.Entity("Api.Models.Especie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastModificationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeCientifico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Nome"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Nome"), new[] { "gin_trgm_ops" });

                    b.HasIndex("NomeCientifico");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NomeCientifico"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NomeCientifico"), new[] { "gin_trgm_ops" });

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("Api.Models.Raca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EspecieId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastModificationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId");

                    b.HasIndex("Nome");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Nome"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Nome"), new[] { "gin_trgm_ops" });

                    b.ToTable("Racas");
                });

            modelBuilder.Entity("Api.Models.Vacina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastModificationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("ReaplicarEmXDias")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("Vacinas");
                });

            modelBuilder.Entity("Api.Models.Animal", b =>
                {
                    b.HasOne("Api.Models.CartaoVacina", "CartaoVacina")
                        .WithMany()
                        .HasForeignKey("CartaoVacinaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Api.Models.Raca", "Raca")
                        .WithMany("Animais")
                        .HasForeignKey("RacaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CartaoVacina");

                    b.Navigation("Raca");
                });

            modelBuilder.Entity("Api.Models.AplicacaoVacina", b =>
                {
                    b.HasOne("Api.Models.CartaoVacina", "CartaoVacina")
                        .WithMany("VacinasAplicadas")
                        .HasForeignKey("CartaoVacinaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Api.Models.Vacina", "Vacina")
                        .WithMany()
                        .HasForeignKey("VacinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CartaoVacina");

                    b.Navigation("Vacina");
                });

            modelBuilder.Entity("Api.Models.Raca", b =>
                {
                    b.HasOne("Api.Models.Especie", "Especie")
                        .WithMany("Racas")
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("Api.Models.CartaoVacina", b =>
                {
                    b.Navigation("VacinasAplicadas");
                });

            modelBuilder.Entity("Api.Models.Especie", b =>
                {
                    b.Navigation("Racas");
                });

            modelBuilder.Entity("Api.Models.Raca", b =>
                {
                    b.Navigation("Animais");
                });
#pragma warning restore 612, 618
        }
    }
}
