// <auto-generated />
using System;
using Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20260913060425_AddNewCampos")]
    partial class AddNewCampos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Animal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("LastModificationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LoteOuPasto")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("OrigemAnimal")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RacaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("RacaId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("Api.Models.AplicacaoVacina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid");

                    b.Property<bool>("CicloFinalizado")
                        .HasColumnType("boolean");

                    b.Property<string>("ComprovanteDocumentoPath")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataAplicacao")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataProximaDose")
                        .HasColumnType("date");

                    b.Property<string>("DoseMl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModificationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroLote")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<int>("StatusComprovante")
                        .HasColumnType("integer");

                    b.Property<Guid>("VacinaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("DataAplicacao");

                    b.HasIndex("DataProximaDose");

                    b.HasIndex("VacinaId");

                    b.ToTable("AplicacoesVacina");
                });

            modelBuilder.Entity("Api.Models.Especie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IconeKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModificationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeCientifico")
                        .HasColumnType("text");

                    b.Property<int>("PortePadrao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Nome"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Nome"), new[] { "gin_trgm_ops" });

                    b.HasIndex("NomeCientifico");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NomeCientifico"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NomeCientifico"), new[] { "gin_trgm_ops" });

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("Api.Models.IdentificadorAnimal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnimalId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModificationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("Valor");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Valor"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Valor"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Valor", "Tipo")
                        .IsUnique();

                    b.ToTable("IdentificadorAnimal");
                });

            modelBuilder.Entity("Api.Models.Raca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EspecieId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastModificationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId");

                    b.HasIndex("Nome");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Nome"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Nome"), new[] { "gin_trgm_ops" });

                    b.ToTable("Racas");
                });

            modelBuilder.Entity("Api.Models.Vacina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<Guid?>("EspecieId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastModificationDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ObrigatorioOrgaoSanitario")
                        .HasColumnType("boolean");

                    b.Property<long>("ReaplicarEmXDias")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId");

                    b.HasIndex("Name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "GIN");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("Vacinas");
                });

            modelBuilder.Entity("Api.Models.Animal", b =>
                {
                    b.HasOne("Api.Models.Raca", "Raca")
                        .WithMany("Animais")
                        .HasForeignKey("RacaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Raca");
                });

            modelBuilder.Entity("Api.Models.AplicacaoVacina", b =>
                {
                    b.HasOne("Api.Models.Animal", "Animal")
                        .WithMany("VacinasAplicadas")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Models.Vacina", "Vacina")
                        .WithMany("Aplicacoes")
                        .HasForeignKey("VacinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Vacina");
                });

            modelBuilder.Entity("Api.Models.IdentificadorAnimal", b =>
                {
                    b.HasOne("Api.Models.Animal", "Animal")
                        .WithMany("Identificadores")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });

            modelBuilder.Entity("Api.Models.Raca", b =>
                {
                    b.HasOne("Api.Models.Especie", "Especie")
                        .WithMany("Racas")
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("Api.Models.Vacina", b =>
                {
                    b.HasOne("Api.Models.Especie", "Especie")
                        .WithMany("VacinasRestritas")
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("Api.Models.Animal", b =>
                {
                    b.Navigation("Identificadores");

                    b.Navigation("VacinasAplicadas");
                });

            modelBuilder.Entity("Api.Models.Especie", b =>
                {
                    b.Navigation("Racas");

                    b.Navigation("VacinasRestritas");
                });

            modelBuilder.Entity("Api.Models.Raca", b =>
                {
                    b.Navigation("Animais");
                });

            modelBuilder.Entity("Api.Models.Vacina", b =>
                {
                    b.Navigation("Aplicacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
