/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/animais": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    RacaId?: string;
                    DataNascimentoFrom?: string;
                    DataNascimentoTo?: string;
                    page?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AnimaReadResponseDto"][];
                        "application/json": components["schemas"]["AnimaReadResponseDto"][];
                        "text/json": components["schemas"]["AnimaReadResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AnimalCreateDto"];
                    "text/json": components["schemas"]["AnimalCreateDto"];
                    "application/*+json": components["schemas"]["AnimalCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AnimalDetailResponseDto"];
                        "application/json": components["schemas"]["AnimalDetailResponseDto"];
                        "text/json": components["schemas"]["AnimalDetailResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/animais/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                    name?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AnimalShortResponseDto"][];
                        "application/json": components["schemas"]["AnimalShortResponseDto"][];
                        "text/json": components["schemas"]["AnimalShortResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/animais/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    RacaId?: string;
                    DataNascimentoFrom?: string;
                    DataNascimentoTo?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/animais/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AnimalDetailResponseDto"];
                        "application/json": components["schemas"]["AnimalDetailResponseDto"];
                        "text/json": components["schemas"]["AnimalDetailResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AnimalPatchDto"];
                    "text/json": components["schemas"]["AnimalPatchDto"];
                    "application/*+json": components["schemas"]["AnimalPatchDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AnimalDetailResponseDto"];
                        "application/json": components["schemas"]["AnimalDetailResponseDto"];
                        "text/json": components["schemas"]["AnimalDetailResponseDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/animais/{id}/prontuario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AnimalProntuarioResponseDto"];
                        "application/json": components["schemas"]["AnimalProntuarioResponseDto"];
                        "text/json": components["schemas"]["AnimalProntuarioResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/aplicacoes-vacina": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                    VacinaId?: string;
                    AnimalId?: string;
                    DataAplicacaoFrom?: string;
                    DataAplicacaoTo?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AplicacaoVacinaReadResponseDto"][];
                        "application/json": components["schemas"]["AplicacaoVacinaReadResponseDto"][];
                        "text/json": components["schemas"]["AplicacaoVacinaReadResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AplicacaoVacinaCreateDto"];
                    "text/json": components["schemas"]["AplicacaoVacinaCreateDto"];
                    "application/*+json": components["schemas"]["AplicacaoVacinaCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AplicacaoVacinaDetailResponseDto"];
                        "application/json": components["schemas"]["AplicacaoVacinaDetailResponseDto"];
                        "text/json": components["schemas"]["AplicacaoVacinaDetailResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/aplicacoes-vacina/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AplicacaoVacinaDetailResponseDto"];
                        "application/json": components["schemas"]["AplicacaoVacinaDetailResponseDto"];
                        "text/json": components["schemas"]["AplicacaoVacinaDetailResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AplicacaoVacinaPatchDto"];
                    "text/json": components["schemas"]["AplicacaoVacinaPatchDto"];
                    "application/*+json": components["schemas"]["AplicacaoVacinaPatchDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AplicacaoVacinaDetailResponseDto"];
                        "application/json": components["schemas"]["AplicacaoVacinaDetailResponseDto"];
                        "text/json": components["schemas"]["AplicacaoVacinaDetailResponseDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/aplicacoes-vacina/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    VacinaId?: string;
                    AnimalId?: string;
                    DataAplicacaoFrom?: string;
                    DataAplicacaoTo?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/aplicacoes-vacina/{id}/comprovante": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/especies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EspecieReadResponseDto"][];
                        "application/json": components["schemas"]["EspecieReadResponseDto"][];
                        "text/json": components["schemas"]["EspecieReadResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EspecieCreateDto"];
                    "text/json": components["schemas"]["EspecieCreateDto"];
                    "application/*+json": components["schemas"]["EspecieCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EspecieDetailResponseDto"];
                        "application/json": components["schemas"]["EspecieDetailResponseDto"];
                        "text/json": components["schemas"]["EspecieDetailResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/especies/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    nomeCientificoToo?: boolean;
                    page?: number | string;
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EspecieShortResponseDto"][];
                        "application/json": components["schemas"]["EspecieShortResponseDto"][];
                        "text/json": components["schemas"]["EspecieShortResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/especies/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/especies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EspecieDetailResponseDto"];
                        "application/json": components["schemas"]["EspecieDetailResponseDto"];
                        "text/json": components["schemas"]["EspecieDetailResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EspeciePatchDto"];
                    "text/json": components["schemas"]["EspeciePatchDto"];
                    "application/*+json": components["schemas"]["EspeciePatchDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EspecieDetailResponseDto"];
                        "application/json": components["schemas"]["EspecieDetailResponseDto"];
                        "text/json": components["schemas"]["EspecieDetailResponseDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/racas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    EspecieId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RacaReadResponseDto"][];
                        "application/json": components["schemas"]["RacaReadResponseDto"][];
                        "text/json": components["schemas"]["RacaReadResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RacaCreateDto"];
                    "text/json": components["schemas"]["RacaCreateDto"];
                    "application/*+json": components["schemas"]["RacaCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RacaDetailResponseDto"];
                        "application/json": components["schemas"]["RacaDetailResponseDto"];
                        "text/json": components["schemas"]["RacaDetailResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/racas/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RacaShortResponseDto"][];
                        "application/json": components["schemas"]["RacaShortResponseDto"][];
                        "text/json": components["schemas"]["RacaShortResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/racas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RacaDetailResponseDto"];
                        "application/json": components["schemas"]["RacaDetailResponseDto"];
                        "text/json": components["schemas"]["RacaDetailResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RacaPatchDto"];
                    "text/json": components["schemas"]["RacaPatchDto"];
                    "application/*+json": components["schemas"]["RacaPatchDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RacaDetailResponseDto"];
                        "application/json": components["schemas"]["RacaDetailResponseDto"];
                        "text/json": components["schemas"]["RacaDetailResponseDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/racas/Throw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/racas/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vacinas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    ReaplicarEmXDiasMin?: number | string;
                    ReaplicarEmXDiasMax?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VacinaReadResponseDto"][];
                        "application/json": components["schemas"]["VacinaReadResponseDto"][];
                        "text/json": components["schemas"]["VacinaReadResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VacinaCreateDto"];
                    "text/json": components["schemas"]["VacinaCreateDto"];
                    "application/*+json": components["schemas"]["VacinaCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VacinaDetailResponseDto"];
                        "application/json": components["schemas"]["VacinaDetailResponseDto"];
                        "text/json": components["schemas"]["VacinaDetailResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vacinas/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VacinaShortResponseDto"][];
                        "application/json": components["schemas"]["VacinaShortResponseDto"][];
                        "text/json": components["schemas"]["VacinaShortResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vacinas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VacinaDetailResponseDto"];
                        "application/json": components["schemas"]["VacinaDetailResponseDto"];
                        "text/json": components["schemas"]["VacinaDetailResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VacinaPatchDto"];
                    "text/json": components["schemas"]["VacinaPatchDto"];
                    "application/*+json": components["schemas"]["VacinaPatchDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VacinaDetailResponseDto"];
                        "application/json": components["schemas"]["VacinaDetailResponseDto"];
                        "text/json": components["schemas"]["VacinaDetailResponseDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/vacinas/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnimalCreateDto: {
            name?: null | string;
            /** Format: date */
            dataNascimento?: string;
            dataNascimentoAproximada?: boolean;
            /** Format: uuid */
            racaId?: null | string;
            sexo?: components["schemas"]["SexoAnimal"];
            origem?: components["schemas"]["OrigemAnimal"];
            loteOuPasto?: null | string;
            identificadores: components["schemas"]["IdentificadorCreateDto"][];
        };
        AnimalDetailResponseDto: {
            /** Format: uuid */
            id?: string;
            name?: null | string;
            /** Format: date */
            dataNascimento?: string;
            dataNascimentoAproximada?: boolean;
            sexo?: components["schemas"]["SexoAnimal"];
            origem?: components["schemas"]["OrigemAnimal"];
            loteOuPasto?: null | string;
            raca?: null | components["schemas"]["RacaDetailResponseDto"];
            identificadores?: components["schemas"]["IdentificadorResponseDto"][];
            identificadorPrincipal?: null | components["schemas"]["IdentificadorResponseDto"];
        };
        AnimalPatchDto: {
            name?: null | string;
            /** Format: date */
            dataNascimento?: null | string;
            dataNascimentoAproximada?: null | boolean;
            /** Format: uuid */
            racaId?: null | string;
            sexo?: null | components["schemas"]["SexoAnimal"];
            origem?: null | components["schemas"]["OrigemAnimal"];
            loteOuPasto?: null | string;
            identificadores?: null | components["schemas"]["IdentificadorCreateDto"][];
        };
        AnimalProntuarioResponseDto: {
            animal: components["schemas"]["AnimalDetailResponseDto"];
            aplicacoesVacina?: components["schemas"]["AplicacaoVacinaDetailResponseDto"][];
        };
        AnimalShortResponseDto: {
            /** Format: uuid */
            id?: string;
            name?: null | string;
        };
        AnimaReadResponseDto: {
            /** Format: uuid */
            id?: string;
            name?: null | string;
            raca?: null | components["schemas"]["RacaShortResponseDto"];
            /** Format: date */
            dataNascimento?: string;
        };
        AplicacaoVacinaCreateDto: {
            /** Format: uuid */
            animalId: string;
            /** Format: uuid */
            vacinaId: string;
            /** Format: date */
            dataAplicacao?: string;
            /** Format: date */
            dataProximaDose?: null | string;
            numeroLote: string;
            laboratorioFabricante?: null | string;
            /** Format: double */
            doseMl?: null | number | string;
            veterinarioResponsavel: string;
            aplicador?: null | string;
            observacoes?: null | string;
        };
        AplicacaoVacinaDetailResponseDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            animalId?: string;
            /** Format: uuid */
            vacinaId?: string;
            vacina?: null | components["schemas"]["VacinaDetailResponseDto"];
            /** Format: date */
            dataAplicacao?: string;
            /** Format: date */
            dataProximaDose?: string;
            numeroLote: string;
            laboratorioFabricante?: null | string;
            /** Format: double */
            doseMl?: null | number | string;
            veterinarioResponsavel: string;
            aplicador?: null | string;
            observacoes?: null | string;
            statusComprovante?: components["schemas"]["StatusComprovanteVacina"];
            temComprovanteAnexo?: boolean;
            /** Format: date-time */
            criadoEm?: string;
            /** Format: date-time */
            atualizadoEm?: null | string;
        };
        AplicacaoVacinaPatchDto: {
            /** Format: date */
            dataAplicacao?: null | string;
            /** Format: date */
            dataProximaDose?: null | string;
            numeroLote?: null | string;
            laboratorioFabricante?: null | string;
            /** Format: double */
            doseMl?: null | number | string;
            veterinarioResponsavel?: null | string;
            aplicador?: null | string;
            observacoes?: null | string;
        };
        AplicacaoVacinaReadResponseDto: {
            /** Format: uuid */
            id?: string;
            vacina: components["schemas"]["VacinaShortResponseDto"];
            /** Format: uuid */
            animalId?: string;
            /** Format: date */
            dataAplicacao?: string;
        };
        EspecieCreateDto: {
            nome: string;
            nomeCientifico?: null | string;
            portePadrao?: components["schemas"]["PorteAnimal"];
            iconeKey?: string;
        };
        EspecieDetailResponseDto: {
            /** Format: uuid */
            id?: string;
            nome: string;
            nomeCientifico?: null | string;
            portePadrao?: components["schemas"]["PorteAnimal"];
            iconeKey?: string;
            /** Format: uint32 */
            raceCount?: number | string;
        };
        EspeciePatchDto: {
            nome?: null | string;
            nomeCientifico?: null | string;
            portePadrao?: null | components["schemas"]["PorteAnimal"];
            iconeKey?: null | string;
        };
        EspecieReadResponseDto: {
            /** Format: uuid */
            id?: string;
            nome: string;
            nomeCientifico?: null | string;
            portePadrao?: components["schemas"]["PorteAnimal"];
            iconeKey?: string;
        };
        EspecieShortResponseDto: {
            /** Format: uuid */
            id?: string;
            fullName: string;
        };
        IdentificadorCreateDto: {
            tipo: components["schemas"]["TipoIdentificador"];
            valor: string;
            /** @default false */
            ehPrincipal: boolean;
        };
        IdentificadorResponseDto: {
            /** Format: uuid */
            id: string;
            tipo: components["schemas"]["TipoIdentificador"];
            valor: string;
            ehPrincipal: boolean;
        };
        /** Format: binary */
        IFormFile: string;
        OrigemAnimal: number;
        PorteAnimal: number;
        RacaCreateDto: {
            nome: string;
            /** Format: uuid */
            especieId: string;
        };
        RacaDetailResponseDto: {
            /** Format: uuid */
            id?: string;
            nome: string;
            especie: components["schemas"]["EspecieShortResponseDto"];
            /** Format: uint32 */
            animalCount?: number | string;
        };
        RacaPatchDto: {
            nome?: null | string;
        };
        RacaReadResponseDto: {
            /** Format: uuid */
            id?: string;
            nome: string;
            especie: components["schemas"]["EspecieShortResponseDto"];
        };
        RacaShortResponseDto: {
            /** Format: uuid */
            id?: string;
            nome: string;
        };
        SexoAnimal: number;
        StatusComprovanteVacina: number;
        TipoIdentificador: number;
        VacinaCreateDto: {
            name: string;
            /** Format: uint32 */
            reaplicarEmXDias?: number | string;
        };
        VacinaDetailResponseDto: {
            /** Format: uuid */
            id?: string;
            name: string;
            /** Format: uint32 */
            reaplicarEmXDias?: number | string;
            /** Format: date-time */
            criadoEm?: string;
        };
        VacinaPatchDto: {
            name?: null | string;
            /** Format: uint32 */
            reaplicarEmXDias?: null | number | string;
        };
        VacinaReadResponseDto: {
            /** Format: uuid */
            id?: string;
            name: string;
            /** Format: uint32 */
            reaplicarEmXDias?: number | string;
        };
        VacinaShortResponseDto: {
            /** Format: uuid */
            id?: string;
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
