/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/animais": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    RacaId?: string;
                    EspecieId?: string;
                    Sexo?: components["schemas"]["SexoAnimal"];
                    Origem?: components["schemas"]["OrigemAnimal"];
                    OrigemAnimal?: components["schemas"]["OrigemAnimal"];
                    DataNascimento?: string;
                    DataNascimentoFrom?: string;
                    DataNascimentoTo?: string;
                    LoteOuPasto?: string;
                    Ativo?: boolean;
                    Identificador?: string;
                    TipoIdentificador?: components["schemas"]["TipoIdentificador"];
                    CreationDateTimeFrom?: string;
                    CreationDateTimeTo?: string;
                    page?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AnimalReadResponseDto"][];
                        "application/json": components["schemas"]["AnimalReadResponseDto"][];
                        "text/json": components["schemas"]["AnimalReadResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AnimalCreateDto"];
                    "text/json": components["schemas"]["AnimalCreateDto"];
                    "application/*+json": components["schemas"]["AnimalCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AnimalDetailResponseDto"];
                        "application/json": components["schemas"]["AnimalDetailResponseDto"];
                        "text/json": components["schemas"]["AnimalDetailResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/animais/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                    name?: string;
                    search?: string;
                    RacaId?: string;
                    EspecieId?: string;
                    Sexo?: components["schemas"]["SexoAnimal"];
                    Origem?: components["schemas"]["OrigemAnimal"];
                    OrigemAnimal?: components["schemas"]["OrigemAnimal"];
                    DataNascimento?: string;
                    DataNascimentoFrom?: string;
                    DataNascimentoTo?: string;
                    LoteOuPasto?: string;
                    Ativo?: boolean;
                    Identificador?: string;
                    TipoIdentificador?: components["schemas"]["TipoIdentificador"];
                    CreationDateTimeFrom?: string;
                    CreationDateTimeTo?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AnimalShortResponseDto"][];
                        "application/json": components["schemas"]["AnimalShortResponseDto"][];
                        "text/json": components["schemas"]["AnimalShortResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/animais/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    RacaId?: string;
                    EspecieId?: string;
                    Sexo?: components["schemas"]["SexoAnimal"];
                    Origem?: components["schemas"]["OrigemAnimal"];
                    OrigemAnimal?: components["schemas"]["OrigemAnimal"];
                    DataNascimento?: string;
                    DataNascimentoFrom?: string;
                    DataNascimentoTo?: string;
                    LoteOuPasto?: string;
                    Ativo?: boolean;
                    Identificador?: string;
                    TipoIdentificador?: components["schemas"]["TipoIdentificador"];
                    CreationDateTimeFrom?: string;
                    CreationDateTimeTo?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/animais/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AnimalDetailResponseDto"];
                        "application/json": components["schemas"]["AnimalDetailResponseDto"];
                        "text/json": components["schemas"]["AnimalDetailResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AnimalPatchDto"];
                    "text/json": components["schemas"]["AnimalPatchDto"];
                    "application/*+json": components["schemas"]["AnimalPatchDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AnimalDetailResponseDto"];
                        "application/json": components["schemas"]["AnimalDetailResponseDto"];
                        "text/json": components["schemas"]["AnimalDetailResponseDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/animais/{id}/prontuario": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AnimalProntuarioResponseDto"];
                        "application/json": components["schemas"]["AnimalProntuarioResponseDto"];
                        "text/json": components["schemas"]["AnimalProntuarioResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/aplicacoes-vacina": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                    VacinaId?: string;
                    AnimalId?: string;
                    DataAplicacaoFrom?: string;
                    DataAplicacaoTo?: string;
                    DataProximaDoseFrom?: string;
                    DataProximaDoseTo?: string;
                    DataLimite?: string;
                    SomenteAtrasadas?: boolean;
                    PendenteAssinatura?: boolean;
                    Proximas?: boolean;
                    CicloFinalizado?: boolean;
                    StatusComprovante?: components["schemas"]["StatusComprovanteVacina"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AplicacaoVacinaReadResponseDto"][];
                        "application/json": components["schemas"]["AplicacaoVacinaReadResponseDto"][];
                        "text/json": components["schemas"]["AplicacaoVacinaReadResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AplicacaoVacinaCreateDto"];
                    "text/json": components["schemas"]["AplicacaoVacinaCreateDto"];
                    "application/*+json": components["schemas"]["AplicacaoVacinaCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AplicacaoVacinaDetailResponseDto"];
                        "application/json": components["schemas"]["AplicacaoVacinaDetailResponseDto"];
                        "text/json": components["schemas"]["AplicacaoVacinaDetailResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/aplicacoes-vacina/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AplicacaoVacinaDetailResponseDto"];
                        "application/json": components["schemas"]["AplicacaoVacinaDetailResponseDto"];
                        "text/json": components["schemas"]["AplicacaoVacinaDetailResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AplicacaoVacinaPatchDto"];
                    "text/json": components["schemas"]["AplicacaoVacinaPatchDto"];
                    "application/*+json": components["schemas"]["AplicacaoVacinaPatchDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AplicacaoVacinaDetailResponseDto"];
                        "application/json": components["schemas"]["AplicacaoVacinaDetailResponseDto"];
                        "text/json": components["schemas"]["AplicacaoVacinaDetailResponseDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/aplicacoes-vacina/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    VacinaId?: string;
                    AnimalId?: string;
                    DataAplicacaoFrom?: string;
                    DataAplicacaoTo?: string;
                    DataProximaDoseFrom?: string;
                    DataProximaDoseTo?: string;
                    DataLimite?: string;
                    SomenteAtrasadas?: boolean;
                    PendenteAssinatura?: boolean;
                    Proximas?: boolean;
                    CicloFinalizado?: boolean;
                    StatusComprovante?: components["schemas"]["StatusComprovanteVacina"];
                    somenteAtrasadas?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/aplicacoes-vacina/atrasadas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                    animalId?: string;
                    vacinaId?: string;
                    statusComprovante?: components["schemas"]["StatusComprovanteVacina"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AplicacaoVacinaReadResponseDto"][];
                        "application/json": components["schemas"]["AplicacaoVacinaReadResponseDto"][];
                        "text/json": components["schemas"]["AplicacaoVacinaReadResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/aplicacoes-vacina/atrasadas/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    animalId?: string;
                    vacinaId?: string;
                    statusComprovante?: components["schemas"]["StatusComprovanteVacina"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/aplicacoes-vacina/pendentes-assinatura": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                    animalId?: string;
                    vacinaId?: string;
                    statusComprovante?: components["schemas"]["StatusComprovanteVacina"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AplicacaoVacinaReadResponseDto"][];
                        "application/json": components["schemas"]["AplicacaoVacinaReadResponseDto"][];
                        "text/json": components["schemas"]["AplicacaoVacinaReadResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/aplicacoes-vacina/pendentes-assinatura/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    animalId?: string;
                    vacinaId?: string;
                    statusComprovante?: components["schemas"]["StatusComprovanteVacina"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/aplicacoes-vacina/proximas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                    dataLimite?: string;
                    animalId?: string;
                    vacinaId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AplicacaoVacinaReadResponseDto"][];
                        "application/json": components["schemas"]["AplicacaoVacinaReadResponseDto"][];
                        "text/json": components["schemas"]["AplicacaoVacinaReadResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/aplicacoes-vacina/proximas/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    dataLimite?: string;
                    animalId?: string;
                    vacinaId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/aplicacoes-vacina/lote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AplicacaoVacinaLoteCreateDto"];
                    "text/json": components["schemas"]["AplicacaoVacinaLoteCreateDto"];
                    "application/*+json": components["schemas"]["AplicacaoVacinaLoteCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AplicacaoVacinaReadResponseDto"][];
                        "application/json": components["schemas"]["AplicacaoVacinaReadResponseDto"][];
                        "text/json": components["schemas"]["AplicacaoVacinaReadResponseDto"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/aplicacoes-vacina/{id}/comprovante": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/especies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    PortePadrao?: components["schemas"]["PorteAnimal"];
                    page?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EspecieReadResponseDto"][];
                        "application/json": components["schemas"]["EspecieReadResponseDto"][];
                        "text/json": components["schemas"]["EspecieReadResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EspecieCreateDto"];
                    "text/json": components["schemas"]["EspecieCreateDto"];
                    "application/*+json": components["schemas"]["EspecieCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EspecieDetailResponseDto"];
                        "application/json": components["schemas"]["EspecieDetailResponseDto"];
                        "text/json": components["schemas"]["EspecieDetailResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/especies/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    nomeCientificoToo?: boolean;
                    page?: number | string;
                    search?: string;
                    name?: string;
                    PortePadrao?: components["schemas"]["PorteAnimal"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EspecieShortResponseDto"][];
                        "application/json": components["schemas"]["EspecieShortResponseDto"][];
                        "text/json": components["schemas"]["EspecieShortResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/especies/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    PortePadrao?: components["schemas"]["PorteAnimal"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/especies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EspecieDetailResponseDto"];
                        "application/json": components["schemas"]["EspecieDetailResponseDto"];
                        "text/json": components["schemas"]["EspecieDetailResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EspeciePatchDto"];
                    "text/json": components["schemas"]["EspeciePatchDto"];
                    "application/*+json": components["schemas"]["EspeciePatchDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EspecieDetailResponseDto"];
                        "application/json": components["schemas"]["EspecieDetailResponseDto"];
                        "text/json": components["schemas"]["EspecieDetailResponseDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/racas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    EspecieId?: string;
                    page?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RacaReadResponseDto"][];
                        "application/json": components["schemas"]["RacaReadResponseDto"][];
                        "text/json": components["schemas"]["RacaReadResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RacaCreateDto"];
                    "text/json": components["schemas"]["RacaCreateDto"];
                    "application/*+json": components["schemas"]["RacaCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RacaDetailResponseDto"];
                        "application/json": components["schemas"]["RacaDetailResponseDto"];
                        "text/json": components["schemas"]["RacaDetailResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/racas/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                    search?: string;
                    name?: string;
                    EspecieId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RacaShortResponseDto"][];
                        "application/json": components["schemas"]["RacaShortResponseDto"][];
                        "text/json": components["schemas"]["RacaShortResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/racas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RacaDetailResponseDto"];
                        "application/json": components["schemas"]["RacaDetailResponseDto"];
                        "text/json": components["schemas"]["RacaDetailResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RacaPatchDto"];
                    "text/json": components["schemas"]["RacaPatchDto"];
                    "application/*+json": components["schemas"]["RacaPatchDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RacaDetailResponseDto"];
                        "application/json": components["schemas"]["RacaDetailResponseDto"];
                        "text/json": components["schemas"]["RacaDetailResponseDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/racas/Throw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/racas/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    EspecieId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vacinas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    EspecieId?: string;
                    ObrigatorioOrgaoSanitario?: boolean;
                    ReaplicarEmXDiasMin?: number | string;
                    ReaplicarEmXDiasMax?: number | string;
                    page?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VacinaReadResponseDto"][];
                        "application/json": components["schemas"]["VacinaReadResponseDto"][];
                        "text/json": components["schemas"]["VacinaReadResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VacinaCreateDto"];
                    "text/json": components["schemas"]["VacinaCreateDto"];
                    "application/*+json": components["schemas"]["VacinaCreateDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VacinaDetailResponseDto"];
                        "application/json": components["schemas"]["VacinaDetailResponseDto"];
                        "text/json": components["schemas"]["VacinaDetailResponseDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vacinas/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                    search?: string;
                    name?: string;
                    EspecieId?: string;
                    ObrigatorioOrgaoSanitario?: boolean;
                    ReaplicarEmXDiasMin?: number | string;
                    ReaplicarEmXDiasMax?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VacinaShortResponseDto"][];
                        "application/json": components["schemas"]["VacinaShortResponseDto"][];
                        "text/json": components["schemas"]["VacinaShortResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vacinas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VacinaDetailResponseDto"];
                        "application/json": components["schemas"]["VacinaDetailResponseDto"];
                        "text/json": components["schemas"]["VacinaDetailResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VacinaPatchDto"];
                    "text/json": components["schemas"]["VacinaPatchDto"];
                    "application/*+json": components["schemas"]["VacinaPatchDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["VacinaDetailResponseDto"];
                        "application/json": components["schemas"]["VacinaDetailResponseDto"];
                        "text/json": components["schemas"]["VacinaDetailResponseDto"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/vacinas/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    EspecieId?: string;
                    ObrigatorioOrgaoSanitario?: boolean;
                    ReaplicarEmXDiasMin?: number | string;
                    ReaplicarEmXDiasMax?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnimalCreateDto: {
            name?: null | string;
            /** Format: date */
            dataNascimento?: string;
            dataNascimentoAproximada?: boolean;
            /** Format: uuid */
            racaId?: null | string;
            sexo?: components["schemas"]["SexoAnimal"];
            origem?: components["schemas"]["OrigemAnimal"];
            loteOuPasto?: null | string;
            ativo?: boolean;
            identificadores: components["schemas"]["IdentificadorCreateDto"][];
        };
        AnimalDetailResponseDto: {
            /** Format: uuid */
            id?: string;
            name?: null | string;
            /** Format: date */
            dataNascimento?: string;
            dataNascimentoAproximada?: boolean;
            sexo?: components["schemas"]["SexoAnimal"];
            origem?: components["schemas"]["OrigemAnimal"];
            loteOuPasto?: null | string;
            ativo?: boolean;
            raca?: null | components["schemas"]["RacaReadResponseDto"];
            identificadores?: components["schemas"]["IdentificadorResponseDto"][];
            identificadorPrincipal?: null | components["schemas"]["IdentificadorResponseDto"];
            /** Format: date-time */
            creationDateTime?: string;
            /** Format: date-time */
            lastModificationDateTime?: null | string;
        };
        AnimalPatchDto: {
            name?: null | string;
            /** Format: date */
            dataNascimento?: null | string;
            dataNascimentoAproximada?: null | boolean;
            /** Format: uuid */
            racaId?: null | string;
            sexo?: null | components["schemas"]["SexoAnimal"];
            origem?: null | components["schemas"]["OrigemAnimal"];
            loteOuPasto?: null | string;
            ativo?: null | boolean;
            identificadores?: null | components["schemas"]["IdentificadorCreateDto"][];
        };
        AnimalProntuarioResponseDto: {
            animal: components["schemas"]["AnimalDetailResponseDto"];
            aplicacoesVacina?: components["schemas"]["AplicacaoVacinaDetailResponseDto"][];
        };
        AnimalReadResponseDto: {
            /** Format: uuid */
            id?: string;
            name?: null | string;
            sexo?: components["schemas"]["SexoAnimal"];
            origem?: components["schemas"]["OrigemAnimal"];
            /** Format: date */
            dataNascimento?: string;
            loteOuPasto?: null | string;
            ativo?: boolean;
            raca?: null | components["schemas"]["RacaShortResponseDto"];
            identificadorPrincipal?: null | components["schemas"]["IdentificadorResponseDto"];
        };
        AnimalShortResponseDto: {
            /** Format: uuid */
            id?: string;
            name?: null | string;
            identificadorPrincipal?: null | string;
        };
        AplicacaoVacinaCreateDto: {
            /** Format: uuid */
            animalId: string;
            /** Format: uuid */
            vacinaId: string;
            /** Format: date */
            dataAplicacao?: string;
            /** Format: date */
            dataProximaDose?: null | string;
            cicloFinalizado?: null | boolean;
            numeroLote: string;
            doseMl?: unknown;
            observacoes?: null | string;
            veterinarioResponsavel?: null | string;
            aplicador?: null | string;
            laboratorioFabricante?: null | string;
        };
        AplicacaoVacinaDetailResponseDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            animalId?: string;
            /** Format: uuid */
            vacinaId?: string;
            animal?: null | components["schemas"]["AnimalReadResponseDto"];
            vacina?: null | components["schemas"]["VacinaReadResponseDto"];
            /** Format: date */
            dataAplicacao?: string;
            /** Format: date */
            dataProximaDose?: null | string;
            cicloFinalizado?: boolean;
            numeroLote: string;
            doseMl?: unknown;
            observacoes?: null | string;
            veterinarioResponsavel?: null | string;
            aplicador?: null | string;
            laboratorioFabricante?: null | string;
            statusComprovante?: components["schemas"]["StatusComprovanteVacina"];
            comprovanteDocumentoPath?: null | string;
            temComprovanteAnexo?: boolean;
            /** Format: date-time */
            creationDateTime?: string;
            /** Format: date-time */
            lastModificationDateTime?: null | string;
            /** Format: date-time */
            criadoEm?: string;
            /** Format: date-time */
            atualizadoEm?: null | string;
        };
        AplicacaoVacinaLoteCreateDto: {
            /** Format: uuid */
            vacinaId: string;
            numeroLote: string;
            doseMl?: unknown;
            /** Format: date */
            dataAplicacao?: string;
            /** Format: date */
            dataProximaDose?: null | string;
            observacoes?: null | string;
            veterinarioResponsavel?: null | string;
            aplicador?: null | string;
            laboratorioFabricante?: null | string;
            animais: components["schemas"]["ItemAnimalLoteDto"][];
        };
        AplicacaoVacinaPatchDto: {
            /** Format: uuid */
            animalId?: null | string;
            /** Format: uuid */
            vacinaId?: null | string;
            /** Format: date */
            dataAplicacao?: null | string;
            /** Format: date */
            dataProximaDose?: null | string;
            cicloFinalizado?: null | boolean;
            statusComprovante?: null | components["schemas"]["StatusComprovanteVacina"];
            comprovanteDocumentoPath?: null | string;
            numeroLote?: null | string;
            doseMl?: unknown;
            observacoes?: null | string;
            veterinarioResponsavel?: null | string;
            aplicador?: null | string;
            laboratorioFabricante?: null | string;
        };
        AplicacaoVacinaReadResponseDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            animalId?: string;
            /** Format: uuid */
            vacinaId?: string;
            animal?: null | components["schemas"]["AnimalShortResponseDto"];
            vacina?: null | components["schemas"]["VacinaShortResponseDto"];
            /** Format: date */
            dataAplicacao?: string;
            /** Format: date */
            dataProximaDose?: null | string;
            cicloFinalizado?: boolean;
            statusComprovante?: components["schemas"]["StatusComprovanteVacina"];
            comprovanteDocumentoPath?: null | string;
            numeroLote?: string;
            doseMl?: unknown;
            veterinarioResponsavel?: null | string;
            aplicador?: null | string;
            laboratorioFabricante?: null | string;
        };
        EspecieCreateDto: {
            nome: string;
            nomeCientifico?: null | string;
            portePadrao?: components["schemas"]["PorteAnimal"];
            iconeKey?: string;
        };
        EspecieDetailResponseDto: {
            /** Format: uuid */
            id?: string;
            nome: string;
            nomeCientifico?: null | string;
            portePadrao?: components["schemas"]["PorteAnimal"];
            iconeKey?: string;
            /** Format: uint32 */
            raceCount?: number | string;
            racas?: components["schemas"]["RacaReadResponseDto"][];
            vacinasRestritas?: components["schemas"]["VacinaReadResponseDto"][];
            /** Format: date-time */
            creationDateTime?: string;
            /** Format: date-time */
            lastModificationDateTime?: null | string;
        };
        EspeciePatchDto: {
            nome?: null | string;
            nomeCientifico?: null | string;
            portePadrao?: null | components["schemas"]["PorteAnimal"];
            iconeKey?: null | string;
        };
        EspecieReadResponseDto: {
            /** Format: uuid */
            id?: string;
            nome: string;
            nomeCientifico?: null | string;
            portePadrao?: components["schemas"]["PorteAnimal"];
            iconeKey?: string;
            /** Format: uint32 */
            raceCount?: number | string;
        };
        EspecieShortResponseDto: {
            /** Format: uuid */
            id?: string;
            nome: string;
            fullName?: string;
            iconeKey?: string;
        };
        IdentificadorCreateDto: {
            tipo: components["schemas"]["TipoIdentificador"];
            valor: string;
            /** @default false */
            ehPrincipal: boolean;
        };
        IdentificadorResponseDto: {
            /** Format: uuid */
            id: string;
            tipo: components["schemas"]["TipoIdentificador"];
            valor: string;
            ehPrincipal: boolean;
        };
        /** Format: binary */
        IFormFile: string;
        ItemAnimalLoteDto: {
            /** Format: uuid */
            animalId: string;
            cicloFinalizado?: boolean;
        };
        /** @enum {unknown} */
        OrigemAnimal: "Interno" | "Externo";
        /** @enum {unknown} */
        PorteAnimal: "Pequeno" | "Medio" | "Grande";
        RacaCreateDto: {
            nome: string;
            /** Format: uuid */
            especieId: string;
        };
        RacaDetailResponseDto: {
            /** Format: uuid */
            id?: string;
            nome: string;
            /** Format: uuid */
            especieId?: string;
            especie?: null | components["schemas"]["EspecieReadResponseDto"];
            /** Format: uint32 */
            animalCount?: number | string;
            /** Format: date-time */
            creationDateTime?: string;
            /** Format: date-time */
            lastModificationDateTime?: null | string;
        };
        RacaPatchDto: {
            nome?: null | string;
            /** Format: uuid */
            especieId?: null | string;
        };
        RacaReadResponseDto: {
            /** Format: uuid */
            id?: string;
            nome: string;
            /** Format: uuid */
            especieId?: string;
            especie: components["schemas"]["EspecieShortResponseDto"];
        };
        RacaShortResponseDto: {
            /** Format: uuid */
            id?: string;
            nome: string;
        };
        /** @enum {unknown} */
        SexoAnimal: "Femea" | "Macho" | "Indefinido";
        /** @enum {unknown} */
        StatusComprovanteVacina: "NaoEmitido" | "PendenteAssinatura" | "Assinado";
        /** @enum {unknown} */
        TipoIdentificador: "BrincoVisual" | "BrincoEletronico" | "Sisbov" | "Microchip" | "RegistroAssociado" | "Tatuagem" | "NomeUnico";
        VacinaCreateDto: {
            name: string;
            descricao?: null | string;
            /** Format: uint32 */
            reaplicarEmXDias?: number | string;
            obrigatorioOrgaoSanitario?: boolean;
            /** Format: uuid */
            especieId?: null | string;
        };
        VacinaDetailResponseDto: {
            /** Format: uuid */
            id?: string;
            name: string;
            descricao?: null | string;
            /** Format: uint32 */
            reaplicarEmXDias?: number | string;
            obrigatorioOrgaoSanitario?: boolean;
            /** Format: uuid */
            especieId?: null | string;
            especie?: null | components["schemas"]["EspecieReadResponseDto"];
            /** Format: uint32 */
            totalAplicacoes?: number | string;
            /** Format: date-time */
            creationDateTime?: string;
            /** Format: date-time */
            lastModificationDateTime?: null | string;
            /** Format: date-time */
            criadoEm?: string;
        };
        VacinaPatchDto: {
            name?: null | string;
            descricao?: null | string;
            /** Format: uint32 */
            reaplicarEmXDias?: null | number | string;
            obrigatorioOrgaoSanitario?: null | boolean;
            /** Format: uuid */
            especieId?: null | string;
        };
        VacinaReadResponseDto: {
            /** Format: uuid */
            id?: string;
            name: string;
            descricao?: null | string;
            /** Format: uint32 */
            reaplicarEmXDias?: number | string;
            obrigatorioOrgaoSanitario?: boolean;
            /** Format: uuid */
            especieId?: null | string;
            especie?: null | components["schemas"]["EspecieShortResponseDto"];
        };
        VacinaShortResponseDto: {
            /** Format: uuid */
            id?: string;
            name: string;
            descricao?: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
