# Use postgres/example user/password credentials

services:

  api:
    build: .
    working_dir: /app
    volumes:
      - ..:/app
      - nuget-cache:/root/.nuget/packages/

    command: sleep infinity
    environment:
      ConnectionStrings__ApiContext: "Server=db;Database=vacinas;Username=postgres;Password=postgresssss;Port=5432"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "8080:8080"
      - "5173:5173"

  db:
    image: postgres:18-alpine
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: "postgresssss"
      POSTGRES_DATABASE: "vacinas"

volumes:
  db-data:
  nuget-cache:
